services:
  postgres:
    image: postgres:16
    container_name: fastapi_template_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_template
    ports:
      - 5234:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fastapi_template_redis
    restart: always
    ports:
      - 6973:6379
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres:
  redis:
