[project]
name = "fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.1",
    "argon2-cffi>=25.1.0",
    "asyncpg>=0.30.0",
    "discord-py>=2.6.4",
    "fastapi>=0.119.0",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]>=2.12.0",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "redis>=7.0.1",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.37.0",
]

