services:
  postgres:
    image: postgres:18
    container_name: vegate_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - vegate_postgres:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: vegate_redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - vegate_redis:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  http_server:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      no_cache: true
    command: backend run
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

volumes:
  vegate_postgres:
  vegate_redis:
