name: Test
on:
  push:
    branches:
      - development

jobs:
  build:
    name: Test
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          FPATH='.env.test'

          cat <<'EOF' > $FPATH
          ${{ secrets.ENV_TEST_FILE }}
          EOF

          if [ -s $FPATH ]; then
            echo ".env created successfully"
            exit 0
          else
            echo "Failed to create env at $FPATH"
            exit 1
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.11"

      - name: Run tests
        run: uv run pytest -s -v

      - name: Push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # git fetch origin main
          # git checkout main
          # git reset --hard development
          # git push --force origin main

          git fetch origin main
          git checkout main
          git merge --allow-unrelated-histories --no-ff -m "Merge development into main after successful tests" development
          git push origin main
