name: Upstream Workflow

on:
  push:
    branches: ["development"]

jobs:
  push_changes:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Make a change
        run: echo "hello world" > file.txt

      - name: Create Pull Request to Main
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: release/from-dev
          base: main
          title: "Automated Promotion: Dev to Main"
          body: "Tests passed on dev. Merging to main for deployment."
          labels: "automated-pr"
